### ISSUE TITLE
How to read attributes?

### ISSUE THREAD

**Issue by boozook** [cubuspl42/libwap32#1]
Maybe you can help me. Please if you can!

Gruntz, .REZ. Maybe you know how to read (& interpret) `ATTRIBUTEZ.TXT`?
(`.REZ::GAME/ATTRIBUTEZ.TXT`)

**Comment by cubuspl42** [comment]
Sorry, no idea. I've never played Gruntz.
But if you have any troubles with libwap32 and Gruntz maps, please post an issue.

**Comment by Ginden** [comment]
I have found following information:
> It's blowfish-encrypted file with password "1212"
